version: "3"
services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - ./log/next:/root/.npm/_logs/
    command: sh -c "cd $COMPOSE_PROJECT_NAME && npm run dev"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/sites:/etc/nginx/conf.d
      - ./log/nginx:/var/log/nginx
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - next
